"""Automated recruiter / referral outreach on LinkedIn.

After applying to a job, the bot can optionally send a short personalised
message to the recruiter or hiring manager whose profile was captured during
job discovery.  The message is generated by the configured LLM so it reads
naturally and references the specific role.

Enable via work_preferences.yaml:
    recruiter_outreach:
        enabled: true
        daily_limit: 20
        message_style: "professional"   # professional | casual | brief
"""
from __future__ import annotations

import asyncio
import random
from dataclasses import dataclass, field
from typing import Any

from playwright.async_api import Page, TimeoutError as PWTimeout

from src.logging import logger


@dataclass
class OutreachStats:
    sent: int = 0
    skipped: int = 0
    failed: int = 0
    contacted_profiles: set = field(default_factory=set)


class RecruiterOutreach:
    """Send personalised messages to recruiters/hiring managers on LinkedIn."""

    CONNECT_BTN_SELECTOR = "button:has-text('Connect')"
    MESSAGE_BTN_SELECTOR = "button:has-text('Message')"
    MESSAGE_BOX_SELECTOR = ".msg-form__contenteditable"
    SEND_BTN_SELECTOR = "button.msg-form__send-button"
    ADD_NOTE_BTN = "button:has-text('Add a note')"
    NOTE_TEXTAREA = "textarea[name='message']"
    SEND_INVITE_BTN = "button:has-text('Send')"

    def __init__(self, llm=None, daily_limit: int = 20, message_style: str = "professional"):
        self._llm = llm
        self.daily_limit = daily_limit
        self.message_style = message_style
        self.stats = OutreachStats()

    @property
    def can_send(self) -> bool:
        return self.stats.sent < self.daily_limit

    async def send_referral_message(
        self,
        page: Page,
        recruiter_url: str,
        job_title: str,
        company: str,
        candidate_name: str = "",
    ) -> bool:
        """Navigate to a recruiter's LinkedIn profile and send a message.

        Tries the "Message" button first (for existing connections).
        Falls back to "Connect" with a personalised note if available.
        Returns True if the message/invite was sent.
        """
        if not self.can_send:
            logger.info("Recruiter outreach daily limit ({}) reached.", self.daily_limit)
            self.stats.skipped += 1
            return False

        if not recruiter_url or "linkedin.com" not in recruiter_url:
            self.stats.skipped += 1
            return False

        # Avoid contacting the same person twice
        if recruiter_url in self.stats.contacted_profiles:
            self.stats.skipped += 1
            return False

        message = self._generate_message(job_title, company, candidate_name)
        if not message:
            self.stats.failed += 1
            return False

        try:
            await page.goto(recruiter_url, wait_until="domcontentloaded", timeout=20000)
            await asyncio.sleep(random.uniform(2.0, 4.0))

            # Try direct message first
            sent = await self._try_direct_message(page, message)
            if not sent:
                # Fall back to connection invite with note
                sent = await self._try_connect_with_note(page, message)

            if sent:
                self.stats.sent += 1
                self.stats.contacted_profiles.add(recruiter_url)
                logger.info("Recruiter outreach sent to {} for {} @ {}", recruiter_url, job_title, company)
                return True
            else:
                self.stats.failed += 1
                return False

        except Exception as exc:
            logger.warning("Recruiter outreach error for {}: {}", recruiter_url, exc)
            self.stats.failed += 1
            return False

    async def _try_direct_message(self, page: Page, message: str) -> bool:
        """Click "Message" button and send via LinkedIn messaging."""
        try:
            msg_btn = await page.wait_for_selector(
                self.MESSAGE_BTN_SELECTOR, timeout=5000, state="visible"
            )
            await msg_btn.click()
            await asyncio.sleep(random.uniform(1.5, 3.0))

            msg_box = await page.wait_for_selector(
                self.MESSAGE_BOX_SELECTOR, timeout=5000, state="visible"
            )
            await msg_box.fill(message)
            await asyncio.sleep(random.uniform(0.5, 1.5))

            send_btn = await page.query_selector(self.SEND_BTN_SELECTOR)
            if send_btn:
                await send_btn.click()
                await asyncio.sleep(random.uniform(1.0, 2.0))
                return True
            return False

        except Exception as exc:
            logger.debug("Direct message failed: {}", type(exc).__name__)
            return False

    async def _try_connect_with_note(self, page: Page, message: str) -> bool:
        """Click "Connect" and add a personalised note (max 300 chars)."""
        try:
            connect_btn = await page.wait_for_selector(
                self.CONNECT_BTN_SELECTOR, timeout=5000, state="visible"
            )
            await connect_btn.click()
            await asyncio.sleep(random.uniform(1.0, 2.0))

            add_note = await page.wait_for_selector(
                self.ADD_NOTE_BTN, timeout=5000, state="visible"
            )
            await add_note.click()
            await asyncio.sleep(random.uniform(0.5, 1.5))

            note_box = await page.wait_for_selector(
                self.NOTE_TEXTAREA, timeout=5000, state="visible"
            )
            truncated = message[:300]
            await note_box.fill(truncated)
            await asyncio.sleep(random.uniform(0.5, 1.0))

            send_btn = await page.query_selector(self.SEND_INVITE_BTN)
            if send_btn:
                await send_btn.click()
                await asyncio.sleep(random.uniform(1.0, 2.0))
                return True
            return False

        except Exception as exc:
            logger.debug("Direct message failed: {}", type(exc).__name__)
            return False

    # ------------------------------------------------------------------
    # LLM message generation
    # ------------------------------------------------------------------

    def _generate_message(self, job_title: str, company: str, candidate_name: str) -> str:
        """Use the LLM to craft a personalised outreach message."""
        if self._llm is None:
            return self._fallback_message(job_title, company, candidate_name)

        style_hints = {
            "professional": "Write in a polished, professional tone.",
            "casual": "Write in a friendly, approachable tone.",
            "brief": "Keep it under 2 sentences.",
        }
        style = style_hints.get(self.message_style, style_hints["professional"])

        prompt = (
            f"Write a short LinkedIn message (under 250 characters) to a recruiter "
            f"or hiring manager about the '{job_title}' position at {company}. "
            f"{style} "
            f"Express genuine interest in the role and briefly mention relevant skills. "
            f"Do NOT use placeholder brackets. "
            f"Sign off with just a first name{f': {candidate_name.split()[0]}' if candidate_name else ''}."
        )
        try:
            result = self._llm.invoke(prompt)
            if hasattr(result, "content"):
                result = result.content
            return str(result).strip()
        except Exception as exc:
            logger.debug("LLM outreach message generation failed: {}", exc)
            return self._fallback_message(job_title, company, candidate_name)

    @staticmethod
    def _fallback_message(job_title: str, company: str, candidate_name: str) -> str:
        name = candidate_name.split()[0] if candidate_name else ""
        msg = (
            f"Hi! I recently applied for the {job_title} role at {company} "
            f"and would love to connect. I'm excited about the opportunity and "
            f"believe my background is a strong fit."
        )
        if name:
            msg += f" — {name}"
        return msg
